apiVersion: v1
kind: Service
metadata:
  name: hello-db-service
spec:
  selector:
    app: hello-db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
